import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   {
  //     type: "autogenerated",
  //     dirName: ".",
  //   },
  // ],
  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "基础概念",
      items: ["basics/system-task", "basics/technical-analysis"],
    },
    {
      type: "category",
      label: "使用指南",
      items: ["tutorial/create", "tutorial/use", "tutorial/manage"],
    },
    {
      type: "category",
      label: "更多信息",
      items: ["more/log", "more/question", "more/contact"],
    },
  ],
};

export default sidebars;
